//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoricalMuseum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibits()
        {
            this.ExhibitsInHalls = new HashSet<ExhibitsInHalls>();
            this.ExhibitsInStoreroom = new HashSet<ExhibitsInStoreroom>();
        }
    
        public int id { get; set; }
        public string Exhibit { get; set; }
        public int ExhibitType { get; set; }
        public Nullable<int> Author { get; set; }
        public int HistoricalEpoch { get; set; }
        public int CreationCountry { get; set; }
        public string Description { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual HistoricalEpochs HistoricalEpochs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitsInHalls> ExhibitsInHalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitsInStoreroom> ExhibitsInStoreroom { get; set; }
        public virtual ExhibitsTypes ExhibitsTypes { get; set; }
    }
}
