//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoricalMuseum
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallsInTourPrograms
    {
        public int id { get; set; }
        public int TourProgram { get; set; }
        public int Hall { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual TourPrograms TourPrograms { get; set; }
    }
}
